FROM golang:1.9.2-stretch

RUN apt-get update && \
    apt-get -y install \
        ca-certificates \
        curl \
        gcc \
        git \
        libc6-dev \
        libsystemd-dev

WORKDIR /go/src/github.com/castlery/systemd-cloud-watch

COPY . .

CMD make
